/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.biblioteca.presentacion;

import com.biblioteca.controlador.LibroController;
import com.biblioteca.entidad.Categoria;
import com.biblioteca.entidad.Editorial;
import com.biblioteca.entidad.Libro;
import com.biblioteca.repositorio.LibroRepository;
import com.biblioteca.servicio.LibroService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agnar
 */
public class JPLibro extends javax.swing.JPanel {

    LibroRepository repo = new LibroRepository();
    LibroService service = new LibroService(repo);
    LibroController controller = new LibroController(service);

    /**
     * Creates new form JPLibro
     */
    public JPLibro() {
        initComponents();
        txtIdLibro.setText(String.valueOf(controller.obtenerSiguienteId()));
        
        cbCategoria.setModel(new DefaultComboBoxModel(Categoria.values()));
        cbEditorial.setModel(new DefaultComboBoxModel(Editorial.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtIdLibro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbAutor = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbBusqueda = new javax.swing.JComboBox<>();
        checkActivo = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbEditorial = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de libros");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1100, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ISBN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtISBN.setPreferredSize(new java.awt.Dimension(200, 40));
        add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        txtIdLibro.setPreferredSize(new java.awt.Dimension(200, 40));
        add(txtIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("IdLibro");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        txtNombre.setPreferredSize(new java.awt.Dimension(200, 40));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 430, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Autor");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        cbAutor.setPreferredSize(new java.awt.Dimension(200, 40));
        add(cbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cbCategoria.setPreferredSize(new java.awt.Dimension(200, 40));
        add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Categoria");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Editorial");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        cbBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "ISBN", "Nombre", "Categoria" }));
        cbBusqueda.setPreferredSize(new java.awt.Dimension(200, 40));
        add(cbBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        checkActivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkActivo.setSelected(true);
        checkActivo.setText("Esta activo");
        add(checkActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 1020, 210));

        txtCantidad.setPreferredSize(new java.awt.Dimension(200, 40));
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        txtBuscar.setPreferredSize(new java.awt.Dimension(200, 40));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Buscar");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        cbEditorial.setPreferredSize(new java.awt.Dimension(200, 40));
        add(cbEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        controller.guardar(
            txtIdLibro,
            txtISBN,
            txtNombre,
            cbCategoria,
            cbEditorial,
            checkActivo
        );
        
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.setRowCount(0);

        for (Libro l : service.listar()) {
            model.addRow(new Object[]{
                l.getIdLibro(),
                l.getIsbn(),
                l.getNombre(),
                l.getCategoria(),
                l.getEditorial(),
                l.isActivo()
            });
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
        
        txtIdLibro.setText(String.valueOf(controller.obtenerSiguienteId()));
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controller.eliminar(txtIdLibro);
        limpiarFormulario();
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void limpiarFormulario() {
        txtIdLibro.setText("");
        txtISBN.setText("");
        txtNombre.setText("");
        txtCantidad.setText("");

        cbAutor.setSelectedIndex(-1); // nada seleccionado
        cbCategoria.setSelectedIndex(0); // o -1 si querés vacío
        cbEditorial.setSelectedIndex(0);

        checkActivo.setSelected(false);

        txtIdLibro.requestFocus();
    }
    
    private void buscarPorId() {
        int id = Integer.parseInt(txtBuscar.getText());

        Libro l = controller.buscarPorId(id);

        if (l != null) {
            txtIdLibro.setText(String.valueOf(l.getIdLibro()));
            txtISBN.setText(String.valueOf(l.getIsbn()));
            txtNombre.setText(l.getNombre());
            cbCategoria.setSelectedItem(l.getCategoria());
            cbEditorial.setSelectedItem(l.getEditorial());
            checkActivo.setSelected(l.isActivo());
        }
    }

    
    private void buscarPorNombre() {
    List<Libro> lista = controller.buscarPorNombre(txtBuscar.getText());

    DefaultTableModel model = (DefaultTableModel) tabla.getModel();
    model.setRowCount(0);

    for (Libro l : lista) {
        model.addRow(new Object[]{
            l.getIdLibro(),
            l.getNombre(),
            l.getCategoria(),
            l.getEditorial()
        });
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbAutor;
    private javax.swing.JComboBox<String> cbBusqueda;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbEditorial;
    private javax.swing.JCheckBox checkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
